module.exports = {
    "Success" :"Success",
    "contactAdded" :"Contact Addded Successfully",
    "reviewAdded" :"Review Added Successfully",
    "ServerError": "Server error occurred, Please try again",
    "addProductToFavourite": "Product added to favourite list successfully",
    "removeProductToFavourite": "Product removed from favourite list successfully",
    "addShippingAddress": "Shipping Address Added successfully",
    "updateShippingAddress": "Shipping Address Updated successfully",
    "removeShippingAddress": "Shipping Address Deleted successfully",
    "removeProductFromWishList": "Product removed from Wishlist successfully",
    "addProductToWishList": "Product added to WishList successfully",
    "PasswordError": "Invalid password.",
    "missingParamError": "Please check the parameters passed",
    "invalidURL": "Please enter valid URL",
    "invalidVideoFile": "The Size of video must be less then 50Mb",
    "invalidImageFile": "The Size of image must be less then 15Mb",
    "inValidOTP": "Please enter valid otp ",
    "inValidBrand": "Please provide valid brand ID",
    "inValidProduct": "Please provide valid product ID",
    "inValidRating": "Please provide valid rating between 0 to 5",
    "invalidToken": "Invalid Token, Please check again",
    "emailValidationError": "Please enter a valid email addesss",
    "genderValidationError": "Gender should be either male of female",
    "deviceTypeValidationError": "Please enter valid device type",
    "accountTypeValidationError": "Please enter valid Account Type",
    "mobileValidationError": "Please enter valid mobile number",
    "missingParamErrorAdmin":"Please complete all fields to continue",
    "passwordValidationError": "Please enter a valid password",
    "oldAndnewPassnotsame":"Old Password And New Password can't be same",
    "AccountError": "Account not found, Please try again",
    "mobileValidationError": "Please enter a valid mobile number",
    "emailExistError": "An account already exist with same email address",
    "mobileExistError": "An account already exist with same mobile number",
    "registerSuccess": "Register Successfully",
    "loginSuccess": "Login Successfully",
    "otpValidationError": "Invalid otp entered",
    "otpExpired": "Otp has been expired, Please generate again",
    "deviceTypeError": "Invalid device type provided. Allowed ['ios','android']",
	"tokenExpired": "Unauthorised! Access denied",
    "rightsFail": "You are not authorised to perform this action",
    "OtpSent": "Otp sent successfully",
    "invalidCredentials": "Please check your credentials & try again",
    "accountDeactivated": "Your account has been deactivated by admin",
    "mobile_unverified": "Mobile Number not verfied",
    "changePasswordSuccess": "Password Changed Successfully",
    "invalidObjectIdError": "Please Enter valid Object ID",
    "userActivate": "User Activated Successfully",
    "userDeActivate": "User De-Activated Successfully",
    "deleteBrand": "Brand Deleted Successfully",
    "updateBrand": "Brand Updated Successfully",
    "updateProduct": "Product Updated Successfully",
    "deleteProduct": "Product Deleted Successfully",
    "noCelebsForBrand": "No Celebrity Endorsed for that Brand",
    "otpGenerateError": "Error sending otp, please check your mobile number"
} 